[package]
name = "fetch"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
colored = "2.1.0"
cpuid = "0.1.1"
get-shell = "0.1.0"
get_sys_info = "0.1.21"
sysinfo = "0.30.5"
